name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-duckdb
        run: pip install dbt-duckdb

      - name: Run dbt debug
        run: cd dbt_project && dbt debug

      - name: Run dbt compile
        run: cd dbt_project && dbt compile

      - name: Run dbt test
        run: cd dbt_project && dbt test
