name: dbt CD

on:
  push:
    branches:
      - main

jobs:
  dbt_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-duckdb
        run: pip install dbt-duckdb

      - name: Run dbt build (deploy)
        run: cd dbt_project && dbt build
